services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      ALLOWED_HOSTS: 127.0.0.1,0.0.0.0,localhost
      DATABASE_URL: postgres://yotta:yotta@db:5432/yotta # pragma: allowlist secret
      DJANGO_SETTINGS_MODULE: yotta.settings.dev
      MEDIA_DIR: /app/media/
      RECAPTCHA_PRIVATE_KEY: UPDATE_THIS # pragma: allowlist secret
      RECAPTCHA_PUBLIC_KEY: UPDATE_THIS
      REDIS_URL: redis://redis
      SECRET_KEY: local_dev_secret_key
      SECURE_SSL_REDIRECT: 'false'
      STATIC_DIR: /app/static/
      STATIC_URL: /static/
    command: tail -f /dev/null # do nothing forever - exec commands elsewhere
    ports:
      - 8000:8000 # runserver
    develop:
      watch:
        - action: sync
          path: ./
          target: ./app/
      restart: always
    volumes:
      - ./README.md:/app/README.md:delegated,ro
      - ./docs:/app/docs:delegated,ro
      - ./manage.py:/app/manage.py:delegated,ro
      - ./yotta:/app/yotta:delegated,rw
      - ./media:/app/media:delegated,rw
      - ./poetry.lock:/app/poetry.lock:rw
      - ./pyproject.toml:/app/pyproject.toml:rw
      - ./yotta/static_compiled:/app/yotta/static_compiled:rw
      - ./public:/app/public:delegated,ro
    depends_on:
      - db
  db:
    image: postgres:16
    expose:
      - 5432
    environment:
      POSTGRES_DB: yotta
      POSTGRES_USER: yotta
      POSTGRES_PASSWORD: yotta # pragma: allowlist secret
      PGDATABASE: yotta
      PGUSER: yotta
      PGPASSWORD: yotta # pragma: allowlist secret
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none
    volumes:
      - ./database_dumps:/database_dumps:delegated,rw