# Generated by Django 5.0.4 on 2024-05-01 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
        ("images", "0002_alter_customimage_file_alter_customrendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="listing_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose the image you wish to be displayed when this page appears in listings",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="listing_summary",
            field=models.CharField(
                blank=True,
                help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="listing_title",
            field=models.CharField(
                blank=True,
                help_text="Override the page title used when this page appears in listings",
                max_length=255,
            ),
        ),
    ]
