# Generated by Django 5.0.4 on 2024-05-01 16:08

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import yotta.utils.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_listing_image_homepage_listing_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            template="components/blocks/heading_block.html"
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.RichTextBlock(
                            template="components/blocks/paragraph_block.html"
                        ),
                    ),
                    ("image", yotta.utils.blocks.ImageWithCaptionBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [
                                ("code", wagtail.blocks.TextBlock(required=True)),
                                ("language", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    (
                        "image_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    yotta.utils.blocks.ImageWithCaptionBlock(
                                        required=True
                                    ),
                                ),
                                ("text", wagtail.blocks.RichTextBlock(required=True)),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("left", "Left"), ("right", "Right")]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "cards",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "card",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    wagtail.blocks.RichTextBlock(
                                                        required=True
                                                    ),
                                                ),
                                                (
                                                    "link",
                                                    wagtail.blocks.StructBlock(
                                                        [
                                                            (
                                                                "internal_link",
                                                                wagtail.blocks.PageChooserBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                            (
                                                                "external_link",
                                                                wagtail.blocks.URLBlock(
                                                                    required=False
                                                                ),
                                                            ),
                                                        ],
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        required=False
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="introduction",
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="meta_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
