# Generated by Django 5.0.4 on 2024-05-03 13:05

import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import yotta.utils.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_body_homepage_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.TextField(default='Join us in Las Vegas on October 7-9 for an epic large-scale show exploring where this trillion dollar industry goes next...'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_end',
            field=models.CharField(default='HOW WILL DIGITAL INFRASTRUCTURE MEET', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_start',
            field=models.CharField(default='HOW WILL DIGITAL INFRASTRUCTURE MEET', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(template='components/blocks/heading_block.html')), ('paragraph', wagtail.blocks.RichTextBlock(template='components/blocks/paragraph_block.html')), ('intro_with_text_grid', wagtail.blocks.StructBlock([('title_start', wagtail.blocks.CharBlock(required=True)), ('title_middle', wagtail.blocks.CharBlock(required=True)), ('title_end', wagtail.blocks.CharBlock(required=True)), ('intro', wagtail.blocks.RichTextBlock(required=True)), ('text_grid', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True))])))])), ('document', wagtail.documents.blocks.DocumentChooserBlock()), ('image_text', wagtail.blocks.StructBlock([('image', yotta.utils.blocks.ImageWithCaptionBlock(required=True)), ('text', wagtail.blocks.RichTextBlock(required=True))])), ('people_block', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('intro', wagtail.blocks.CharBlock(required=True)), ('people', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True)), ('role', wagtail.blocks.CharBlock(required=True)), ('company', wagtail.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True))])))]))], blank=True, null=True),
        ),
    ]
